logging:
  file:
    max-size: 100MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) %level %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) %level %clr(%logger :) %message%n"

  level:
    root: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/persons
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
        temp:
          use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db-migrations/changelog.xml
    enabled: true
    drop-first: true